### ISSUE TITLE
Linear algebra library

### ISSUE THREAD

**Issue by theVerySharpFlat** [abheekda1/curve-fitting#1]
[I see that you want to optimize for performance](https://github.com/abheekda1/curve-fitting/blob/8864bb00285321aea78fdcb3fd800a4c25db1b5f/src/Matrix.cpp#L4). Perhaps you could check out [glm](https://github.com/g-truc/glm) (which I use for linear algebra in graphics applications). Or Eigen, which Intel apparently helped out with.

**Comment by abheekda1** [comment]
No

**Comment by abheekda1** [comment]
I would use those but I wanna do this myself. Trying out a couple different algorithms to see which one's the best.
